config/routes.rb
Smokestack::Application.routes.draw do

  resources :auth
  resources :auth do
    collection do
      get 'index'
      post 'login'
      post 'logout'
    end
  end

  resources :config_templates
  resources :config_templates do
    member do
      post 'clone'
    end
  end

  resources :jobs
  resources :jobs do
    member do
      post 'clone'
    end
  end

  resources :node_configs

  resources :smoke_tests
  resources :smoke_tests do
    member do
      post 'run_jobs'
    end
  end

  resources :users
  resources :users do
    member do
      get 'password'
    end
  end

  resources :about

  root :to => "smoke_tests#index"

end

app/models/config_template.rb
class ConfigTemplate < ActiveRecord::Base

  validates_presence_of :name, :description, :cookbook_repo_url, :server_group_json, :job_type
  has_and_belongs_to_many :smoke_tests
  has_many :node_configs, :dependent => :destroy, :order => "hostname"

  validate :handle_validate
  def handle_validate
    retval=true
    if self.environment then 
      self.environment.each_line do |line|
        if not line =~ /^\S+=\S+/ then
            errors.add(:base, "Invalid environment line: #{line}")
            retval=false
        end
      end
    end
    return retval
  end

end

app/controllers/config_templates_controller.rb
class ConfigTemplatesController < ApplicationController

  before_filter :require_admin, :except => :index
  before_filter :authorize, :except => :index
  layout "default", :only => :index

  # GET /config_templates
  # GET /config_templates.xml
  def index
    @config_templates = ConfigTemplate.all

    if params[:table_only] then
      render :partial => "table"
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json  { render :json => @config_templates, :only => [:id, :name, :description] }
        format.xml  { render :xml => @config_templates, :only => [:id, :name, :description] }
      end
    end
  end

  # GET /config_templates/1
  # GET /config_templates/1.xml
  def show
    @config_template = ConfigTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @config_template }
      format.xml  { render :xml => @config_template }
    end
  end

  # GET /config_templates/new
  # GET /config_templates/new.xml
  def new
    @config_template = ConfigTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @config_template }
      format.xml  { render :xml => @config_template }
    end
  end

  # GET /config_templates/1/edit
  def edit
    @config_template = ConfigTemplate.find(params[:id])
  end

  # POST /config_templates
  # POST /config_templates.xml
  def create
    @config_template = ConfigTemplate.new(params[:config_template])

    respond_to do |format|
      if @config_template.save
        format.html { redirect_to(@config_template, :notice => 'ConfigTemplate was successfully created.') }
        format.json  { render :json => @config_template, :status => :created, :location => @config_template }
        format.xml  { render :xml => @config_template, :status => :created, :location => @config_template }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @config_template.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @config_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /config_templates/1
  # PUT /config_templates/1.xml
  def update
    @config_template = ConfigTemplate.find(params[:id])

    respond_to do |format|
      if @config_template.update_attributes(params[:config_template])
        format.html { redirect_to(@config_template, :notice => 'ConfigTemplate was successfully updated.') }
        format.json  { render :json => @config_template, :status => :ok }
        format.xml  { render :xml => @config_template, :status => :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @config_template.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @config_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /config_templates/1
  # DELETE /config_templates/1.xml
  def destroy
    @config_template = ConfigTemplate.find(params[:id])
    json=@config_template.to_json
    xml=@config_template.to_xml

    @config_template.destroy

    respond_to do |format|
      format.html { redirect_to(config_templates_url) }
      format.json  { render :json => json }
      format.xml  { render :xml => xml }
    end

  end

  # POST /config_templates/1/clone
  def clone

    orig = ConfigTemplate.find(params[:id])

    @config_template = ConfigTemplate.new(
        :job_type => orig.job_type,
        :name => orig.name + " Clone",
        :description => orig.description + " Clone",
        :cookbook_repo_url => orig.cookbook_repo_url,
        :environment => orig.environment,
        :server_group_json => orig.server_group_json
    )

    respond_to do |format|
      if @config_template.save

        orig.node_configs.each do |node_config|
            NodeConfig.create(
                :config_template_id => @config_template.id,
                :hostname => node_config.hostname,
                :config_data => node_config.config_data
            )
        end
        format.html { redirect_to(@config_template, :notice => 'ConfigTemplate was successfully cloned.') }
        format.json  { render :json => @config_template, :status => :created, :location => @config_template }
        format.xml  { render :xml => @config_template, :status => :created, :location => @config_template }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @config_template.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @config_template.errors, :status => :unprocessable_entity }
      end

    end

  end

end

app/helpers/config_templates_helper.rb
module ConfigTemplatesHelper
end

app/views/config_templates/_form.html.erb
<div id="config-template-error-messages" />

<%= form_for(@config_template, :html => { :id => "config-template-form", :onsubmit => "create_config_template(); return false;", :class => "form-inline" } ) do |f| %>
  <% if @config_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@config_template.errors.count, "error") %> prohibited this config_template from being saved:</h2>

      <ul>
      <% @config_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :enabled %>
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :job_type %>
    <%= f.select("job_type", Job::JOB_TYPES) %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cookbook_repo_url %>
    <%= f.text_field :cookbook_repo_url, :size => "60" %>
  </div>

<div>
  <h3>Server Group</h3>
  <div>
    <%= f.label :server_group_json %>
    <%= f.text_area :server_group_json, :cols => "80", :class => "wide" %>
  </div>

  <h3>Environment</h3>
  <div>
    <%= f.label :environment %>
    <%= f.text_area :environment, :cols => "80", :class => "wide" %>
  </div>

</div>

<% end %>

app/views/config_templates/_table.html.erb
  <tr class="header">
    <th>Name</th>
    <th>Description</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @config_templates.each do |config_template| %>
  <tr id="config-template-tr-<%= config_template.id %>" class="<%= cycle "tr0", "tr1" %>">
    <td><%= raw(chop_for_html(config_template.name, 40)) %></td>
    <td><%= raw(chop_for_html(config_template.description, 60)) %></td>
    <td><%= yes_no(config_template.enabled) %></td>
    <td><a href="<%= edit_config_template_path(config_template) %>" class="config-template-edit btn btn-small" title="Edit"><i class="icon-edit"></i>Edit</a></td>
    <td><a href="<%= "/node_configs?config_template_id=#{config_template.id}" %>" class="config-template-nodes btn btn-small" title="Node Configs"><i class="icon-asterisk"></i>Node Configs</a></td>
    <td><a href="<%= "/config_templates/#{config_template.id}/clone" %>" class="config-template-clone btn btn-small" title="Clone"><i class="icon-share"></i>Clone</a></td>
    <td><a href="<%= "/config_templates/#{config_template.id}" %>" class="config-template-destroy btn btn-small" title="Delete"><i class="icon-trash"></i></a></td>
  </tr>
<% end %>

app/views/config_templates/edit.html.erb
<%= render 'form' %>

app/views/config_templates/index.html.erb
<button class="btn btn-small" id="config-template-new-button">New Config Template</button>

<script type="text/javascript">

$('.navbar li').removeClass('active');
$('#nav_config_templates').addClass('active');

$(document).ready(function() {

    config_template_selectors();
    config_template_table_selectors();

});

</script>

<%= form_tag('/config_templates/XX', :method => :clone, :id => "config-template-clone-form") %>
</form>

<%= form_tag('/config_templates/XX', :method => :delete, :id => "config-template-delete-form") %>
</form>

<table id="config-templates-table" class="data table-bordered">
    <%= render :partial => 'table' %>
</table>

app/views/config_templates/new.html.erb
<h3>New config template</h3>
<%= render 'form' %>

app/views/config_templates/show.html.erb
<p>
  <b>Name:</b>
  <%= @config_template.name %>
</p>

<p>
  <b>Description:</b>
  <%= @config_template.description %>
</p>

<p>
  <b>Cookbook Repo URL:</b>
  <%= @config_template.cookbook_repo_url %>
</p>

<p>
  <b>Server Group JSON:</b>
<br/>
<textarea rows="10" cols="80">
  <%= @config_template.server_group_json %>
</textarea>
</p>