config/routes.rb
Smokestack::Application.routes.draw do

  resources :auth
  resources :auth do
    collection do
      get 'index'
      post 'login'
      post 'logout'
    end
  end

  resources :config_templates
  resources :config_templates do
    member do
      post 'clone'
    end
  end

  resources :jobs
  resources :jobs do
    member do
      post 'clone'
    end
  end

  resources :node_configs

  resources :smoke_tests
  resources :smoke_tests do
    member do
      post 'run_jobs'
    end
  end

  resources :users
  resources :users do
    member do
      get 'password'
    end
  end

  resources :about

  root :to => "smoke_tests#index"

end

app/models/smoke_test.rb
class SmokeTest < ActiveRecord::Base

  validates_presence_of :description
  has_many :job_groups
  has_one :most_recent_job_group, :class_name => "JobGroup", :order => 'created_at DESC'

  has_many :package_builders
  has_many :config_modules

  has_one :nova_package_builder
  accepts_nested_attributes_for :nova_package_builder

  has_one :glance_package_builder
  accepts_nested_attributes_for :glance_package_builder

  has_one :keystone_package_builder
  accepts_nested_attributes_for :keystone_package_builder

  has_one :swift_package_builder
  accepts_nested_attributes_for :swift_package_builder

  has_one :cinder_package_builder
  accepts_nested_attributes_for :cinder_package_builder

  has_one :neutron_package_builder
  accepts_nested_attributes_for :neutron_package_builder

  has_one :ceilometer_package_builder
  accepts_nested_attributes_for :ceilometer_package_builder

  has_one :heat_package_builder
  accepts_nested_attributes_for :heat_package_builder

  # config modules (puppet, etc)
  has_one :nova_config_module
  accepts_nested_attributes_for :nova_config_module

  has_one :glance_config_module
  accepts_nested_attributes_for :glance_config_module

  has_one :keystone_config_module
  accepts_nested_attributes_for :keystone_config_module

  has_one :swift_config_module
  accepts_nested_attributes_for :swift_config_module

  has_one :cinder_config_module
  accepts_nested_attributes_for :cinder_config_module

  has_one :neutron_config_module
  accepts_nested_attributes_for :neutron_config_module

  has_one :ceilometer_config_module
  accepts_nested_attributes_for :ceilometer_config_module

  has_one :heat_config_module
  accepts_nested_attributes_for :heat_config_module

  has_and_belongs_to_many :config_templates
  has_and_belongs_to_many :test_suites

  before_destroy :handle_before_destroy
  def handle_before_destroy
    self.job_groups.each do |job_groups|
      job_groups.destroy
    end
  end

  validate :handle_validate
  def handle_validate
    retval=true
    if self.config_templates.size > 0 or self.test_suites.size > 0 then
      if self.config_templates.size == 0 then
        errors.add(:base, "At least one configuration must be selected.")
        retval=false
      end
      if self.test_suites.size == 0 then
        errors.add(:base, "At least one test suite must be selected.")
        retval=false
      end
    elsif not self.unit_tests
      errors.add(:base, "At least one test suite must be selected.")
      retval=false
    end
    return retval
  end

  before_save :handle_before_save 
  def handle_before_save
    self.project = nil
    if self.nova_package_builder and self.nova_package_builder.branch != 'master' then
      self.project = 'nova'
    elsif self.glance_package_builder and self.glance_package_builder.branch != 'master' then
      self.project = 'glance'
    elsif self.keystone_package_builder and self.keystone_package_builder.branch != 'master' then
      self.project = 'keystone'
    elsif self.swift_package_builder and self.swift_package_builder.branch != 'master' then
      self.project = 'swift'
    elsif self.cinder_package_builder and self.cinder_package_builder.branch != 'master' then
      self.project = 'cinder'
    elsif self.neutron_package_builder and self.neutron_package_builder.branch != 'master' then
      self.project = 'neutron'
    elsif self.ceilometer_package_builder and self.ceilometer_package_builder.branch != 'master' then
      self.project = 'ceilometer'
    elsif self.heat_package_builder and self.heat_package_builder.branch != 'master' then
      self.project = 'heat'
    end

    # Puppet module project settings
    if self.nova_config_module and self.nova_config_module.branch != 'master' then
      self.project = 'puppet-nova'
    elsif self.glance_config_module and self.glance_config_module.branch != 'master' then
      self.project = 'puppet-glance'
    elsif self.keystone_config_module and self.keystone_config_module.branch != 'master' then
      self.project = 'puppet-keystone'
    elsif self.swift_config_module and self.swift_config_module.branch != 'master' then
      self.project = 'puppet-swift'
    elsif self.cinder_config_module and self.cinder_config_module.branch != 'master' then
      self.project = 'puppet-cinder'
    elsif self.neutron_config_module and self.neutron_config_module.branch != 'master' then
      self.project = 'puppet-neutron'
    elsif self.ceilometer_config_module and self.ceilometer_config_module.branch != 'master' then
      self.project = 'puppet-ceilometer'
    elsif self.heat_config_module and self.heat_config_module.branch != 'master' then
      self.project = 'puppet-heat'
    end

  end

  def as_json(options={})
    hash = {'smoke_test' => super}
    package_builders.each do |builder|
      builder_type = builder.type.chomp('PackageBuilder').downcase
      key = "#{builder_type}_package_builder"
      #hash['smoke_test'].store(key, builder.as_json[key])
      hash['smoke_test'].store(key, builder.as_json)
    end
    config_modules.each do |conf_mod|
      mod_type = conf_mod.type.chomp('ConfigModule').downcase
      key = "#{mod_type}_config_module"
      #hash['smoke_test'].store(key, conf_mod.as_json[key])
      hash['smoke_test'].store(key, conf_mod.as_json)
    end
    hash
  end

end

app/controllers/smoke_tests_controller.rb
class SmokeTestsController < ApplicationController

  before_filter :authorize, :except => [:index, :show]
  layout "default", :only => :index

  SMOKE_TESTS_OBJ_INCLUDES = [
    :package_builders,
    :config_modules
  ]

  # GET /smoke_tests
  # GET /smoke_tests.json
  # GET /smoke_tests.xml
  def index
    @smoke_tests = SmokeTest.find(:all, :include => SMOKE_TESTS_OBJ_INCLUDES, :order => [:project, :id])

    if params[:table_only] then
      render :partial => "table"
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json  { render :json => @smoke_tests } #formatted via as_json
        format.xml  { render :xml => @smoke_tests, :include => SMOKE_TESTS_OBJ_INCLUDES }
      end
    end
  end

  # GET /smoke_tests/1
  # GET /smoke_tests/1.json
  # GET /smoke_tests/1.xml
  def show
    @smoke_test = SmokeTest.find(params[:id], :include => SMOKE_TESTS_OBJ_INCLUDES)

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @smoke_test } #formated via as_json
      format.xml  { render :xml => @smoke_test, :include => SMOKE_TESTS_OBJ_INCLUDES }
    end
  end

  # GET /smoke_tests/new
  # GET /smoke_tests/new.xml
  def new
    @smoke_test = SmokeTest.new
    # package builders
    @smoke_test.build_nova_package_builder
    @smoke_test.nova_package_builder.merge_trunk = false
    @smoke_test.build_glance_package_builder
    @smoke_test.glance_package_builder.merge_trunk = false
    @smoke_test.build_keystone_package_builder
    @smoke_test.keystone_package_builder.merge_trunk = false
    @smoke_test.build_swift_package_builder
    @smoke_test.swift_package_builder.merge_trunk = false
    @smoke_test.build_cinder_package_builder
    @smoke_test.cinder_package_builder.merge_trunk = false
    @smoke_test.build_neutron_package_builder
    @smoke_test.neutron_package_builder.merge_trunk = false
    @smoke_test.build_ceilometer_package_builder
    @smoke_test.ceilometer_package_builder.merge_trunk = false
    @smoke_test.build_heat_package_builder
    @smoke_test.heat_package_builder.merge_trunk = false

    # config modules
    @smoke_test.build_nova_config_module
    @smoke_test.nova_config_module.merge_trunk = false
    @smoke_test.build_glance_config_module
    @smoke_test.glance_config_module.merge_trunk = false
    @smoke_test.build_keystone_config_module
    @smoke_test.keystone_config_module.merge_trunk = false
    @smoke_test.build_swift_config_module
    @smoke_test.swift_config_module.merge_trunk = false
    @smoke_test.build_cinder_config_module
    @smoke_test.cinder_config_module.merge_trunk = false
    @smoke_test.build_neutron_config_module
    @smoke_test.neutron_config_module.merge_trunk = false
    @smoke_test.build_ceilometer_config_module
    @smoke_test.ceilometer_config_module.merge_trunk = false
    @smoke_test.build_heat_config_module
    @smoke_test.heat_config_module.merge_trunk = false

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @smoke_test }
      format.xml  { render :xml => @smoke_test }
    end
  end

  # GET /smoke_tests/1/edit
  def edit
    @smoke_test = SmokeTest.find(params[:id])
  end

  # POST /smoke_tests
  # POST /smoke_tests.xml
  def create
    @smoke_test = SmokeTest.new(params[:smoke_test])

    respond_to do |format|
      if @smoke_test.save
        format.html { redirect_to(@smoke_test, :notice => 'Smoke test was successfully created.') }
        format.json  { render :json => @smoke_test, :status => :created, :location => @smoke_test }
        format.xml  { render :xml => @smoke_test, :status => :created, :location => @smoke_test }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @smoke_test.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @smoke_test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /smoke_tests/1
  # PUT /smoke_tests/1.xml
  def update
    @smoke_test = SmokeTest.find(params[:id])

    if not params[:smoke_test][:test_suite_ids] and not params[:smoke_test][:config_templates]
      @smoke_test.config_templates.clear
      @smoke_test.test_suites.clear
    end
    respond_to do |format|
      if @smoke_test.update_attributes(params[:smoke_test])

        @smoke_test.test_suites.clear if @smoke_test.test_suites.size == 0
        format.html { redirect_to(@smoke_test, :notice => 'Smoke test was successfully updated.') }
        format.json  { render :json => @smoke_test, :status => :ok }
        format.xml  { render :xml => @smoke_test, :status => :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @smoke_test.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @smoke_test.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /smoke_tests/1
  # DELETE /smoke_tests/1.xml
  def destroy
    @smoke_test = SmokeTest.find(params[:id])
    @smoke_test.destroy

    respond_to do |format|
      format.html { redirect_to(smoke_tests_url) }
      format.json  { head :ok }
      format.xml  { head :ok }
    end
  end

  # POST /smoke_tests/1/run_jobs
  def run_jobs
    @smoke_test = SmokeTest.find(params[:id])

    job_group=JobGroup.create(
        :smoke_test => @smoke_test
    )

    respond_to do |format|
      format.html  { head :ok }
      format.json  { head :ok }
      format.xml  { head :ok }
    end

  end

end

app/helpers/smoke_tests_helper.rb
module SmokeTestsHelper

  def config_template_checked(config_template)

    if @smoke_test and @smoke_test.config_templates
      return @smoke_test.config_templates.include?(config_template)
    else
      false
    end

  end

  def test_suite_checked(suite)

    if @smoke_test.new_record? then
      return suite.enabled?
    end

    if @smoke_test and @smoke_test.test_suites
      return @smoke_test.test_suites.include?(suite)
    else
      false 
    end

  end

  def project_branch_name(smoke_test)

    return '' if smoke_test.nil?

    project = smoke_test.project

    return ': master' if project.nil?

    return case project
      when 'nova' then
        builder = smoke_test.package_builders.select{|x| x.type == 'NovaPackageBuilder'}[0]
        if builder then
          'Nova: ' + builder.branch
        else
          'Nova: master'
        end
      when 'glance' then
        builder = smoke_test.package_builders.select{|x| x.type == 'GlancePackageBuilder'}[0]
        if builder then
          'Glance: ' + builder.branch
        else
          'Glance: master'
        end
      when 'keystone' then
        builder = smoke_test.package_builders.select{|x| x.type == 'KeystonePackageBuilder'}[0]
        if builder then
          'Keystone: ' + builder.branch
        else
          'Keystone: master'
        end
      when 'swift' then
        builder = smoke_test.package_builders.select{|x| x.type == 'SwiftPackageBuilder'}[0]
        if builder then
          'Swift: ' + builder.branch
        else
          'Swift: master'
        end
      when 'cinder' then
        builder = smoke_test.package_builders.select{|x| x.type == 'CinderPackageBuilder'}[0]
        if builder then
          'Cinder: ' + builder.branch
        else
          'Cinder: master'
        end
      when 'neutron' then
        builder = smoke_test.package_builders.select{|x| x.type == 'NeutronPackageBuilder'}[0]
        if builder then
          'Neutron: ' + builder.branch
        else
          'Neutron: master'
        end
      when 'ceilometer' then
        builder = smoke_test.package_builders.select{|x| x.type == 'CeilometerPackageBuilder'}[0]
        if builder then
          'Ceilometer: ' + builder.branch
        else
          'Ceilometer: master'
        end
      when 'heat' then
        builder = smoke_test.package_builders.select{|x| x.type == 'HeatPackageBuilder'}[0]
        if builder then
          'Heat: ' + builder.branch
        else
          'Heat: master'
        end
      when 'puppet-nova' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'NovaConfigModule'}[0]
        if conf_module then
          'Puppet Nova: ' + conf_module.branch
        else
          'Puppet Nova: master'
        end
      when 'puppet-glance' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'GlanceConfigModule'}[0]
        if conf_module then
          'Puppet Glance: ' + conf_module.branch
        else
          'Puppet Glance: master'
        end
      when 'puppet-keystone' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'KeystoneConfigModule'}[0]
        if conf_module then
          'Puppet Keystone: ' + conf_module.branch
        else
          'Puppet Keystone: master'
        end
      when 'puppet-swift' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'SwiftConfigModule'}[0]
        if conf_module then
          'Puppet Swift: ' + conf_module.branch
        else
          'Puppet Swift: master'
        end
      when 'puppet-cinder' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'CinderConfigModule'}[0]
        if conf_module then
          'Puppet Cinder: ' + conf_module.branch
        else
          'Puppet Cinder: master'
        end
      when 'puppet-neutron' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'NeutronConfigModule'}[0]
        if conf_module then
          'Puppet Neutron: ' + conf_module.branch
        else
          'Puppet Neutron: master'
        end
      when 'puppet-ceilometer' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'CeilometerConfigModule'}[0]
        if conf_module then
          'Puppet Ceilometer: ' + conf_module.branch
        else
          'Puppet Ceilometer: master'
        end
      when 'puppet-heat' then
        conf_module = smoke_test.config_modules.select{|x| x.type == 'HeatConfigModule'}[0]
        if conf_module then
          'Puppet Heat: ' + conf_module.branch
        else
          'Puppet Heat: master'
        end
      else ': master'
    end 

  end

  #has this builder been modified from default settings
  def is_builder_stock(package_builder)
    if package_builder.new_record? then
      return true
    else
      builder_type = package_builder.type.chomp('PackageBuilder').upcase
      return false if package_builder.url != ENV["#{builder_type}_GIT_MASTER"]
      return false if package_builder.branch != 'master'
      return false if not package_builder.packager_url.blank?
      return false if not package_builder.packager_branch.blank?
      return false if not package_builder.revision_hash.blank?
    end
    return true
  end

  #has this config_module been modified from default settings
  def is_config_module_stock(config_module)
    if config_module.new_record? then
      return true
    else
      conf_module_type = config_module.type.chomp('ConfigModule').upcase
      return false if config_module.url != ENV["PUPPET_#{conf_module_type}_GIT_MASTER"]
      return false if config_module.branch != 'master'
      return false if not config_module.revision_hash.blank?
    end
    return true
  end

end

app/views/smoke_tests/_table.html.erb
  <tr class="header">
    <th>Description</th>
    <th>Project: Branch</th>
    <th>Status</th>
    <th>Updated at</th>
    <th></th>
    <% if is_user %>
      <th></th>
      <th></th>
      <th></th>
    <% end %>
  </tr>

<% show_edit_links = is_user %>

<% @smoke_tests.each do |smoke_test| %>
  <tr id="smoke-test-tr-<%= smoke_test.id %>" class="<%= cycle "tr0", "tr1" %>">
    <td><%= raw(chop_for_html(smoke_test.description, 60)) %></td>
    <td><%=raw chop_for_html(project_branch_name(smoke_test), 40) %></td>
    <td><%=raw status_image(smoke_test.status) %></td>
    <td><%= timestamp(smoke_test.updated_at.in_time_zone) %></td>
    <td><a href="<%= "/smoke_tests/#{smoke_test.id}" %>" class="smoke-test-show btn btn-small" title="Show"><i class="icon-zoom-in"></i></a></td>
    <% if show_edit_links %>
      <td><a href="<%= edit_smoke_test_path(smoke_test) %>" class="smoke-test-edit btn btn-small" title="Edit"><i class="icon-edit"></i>Edit</a></td>
      <td><a href="<%= "/smoke_tests/#{smoke_test.id}" %>" class="smoke-test-destroy btn btn-small" title="Delete"><i class="icon-trash"></i></a></td>
      <td><a href="<%= "/smoke_tests/#{smoke_test.id}/run_jobs" %>" class="smoke-test-run-jobs btn btn-small" title="Fire (Run Jobs)"><i class="icon-fire"></i>Fire</a></td>
    <% end %>
  </tr>
<% end %>

app/views/smoke_tests/edit.html.erb
<h3>Editing Test Configuration</h3>

<%= render 'form' %>

app/views/smoke_tests/index.html.erb
<% if is_user %>
<button class="btn btn-small" id="smoke-test-new-button">New Smoke Test</button>
<% end %>

<script type="text/javascript">

$('.navbar li').removeClass('active');
$('#nav_smoke_tests').addClass('active');

$(document).ready(function() {

  smoke_test_selectors();
  smoke_test_table_selectors();

});

</script>

<form action="/smoke_tests/XX" method="POST" id="smoke-test-delete-form">
<input type="hidden" name="_method" value="delete"/>
<%= tag(:input, :type => "hidden", 
    :name => request_forgery_protection_token.to_s, 
    :value => form_authenticity_token) %>
</form>

<form action="/smoke_tests/XX/run_jobs" method="POST" id="smoke-test-job-form">
<input type="hidden" name="_method" value="post"/>
<%= tag(:input, :type => "hidden", 
    :name => request_forgery_protection_token.to_s, 
    :value => form_authenticity_token) %>
</form>

<table id="smoke-tests-table" class="data table-condensed table-bordered">
  <%= render :partial => 'table' %>
</table>

app/views/smoke_tests/new.html.erb
<h3>New Test Configuration</h3>

<%= render 'form' %>

app/views/smoke_tests/show.html.erb
<p id="notice"><%= notice %></p>
<b>Description:</b> <%= @smoke_test.description %>
<br/>
<b>Created at:</b> <%= timestamp(@smoke_test.created_at.in_time_zone) %>
<br/>
<b>Updated at:</b> <%= timestamp(@smoke_test.created_at.in_time_zone) %>
<br/>

<hr/>
<% @smoke_test.package_builders.each do |builder| %>
<% if not is_builder_stock(builder) then %>
<% builder_type = builder.type.chomp('PackageBuilder').downcase %>
<h4><%= builder_type.upcase %> Package Builder</h4>
<b>URL:</b> <%= builder.url %>
<br/>
<% if not builder.branch.blank? then %>
<b>Branch:</b><%= builder.branch %>
<br/>
<% end %>
<b>Merge trunk:</b><%= yes_no(builder.merge_trunk) %>
<br/>
<b>Revision (most recent):</b>
<% if @smoke_test.most_recent_job_group and @smoke_test.most_recent_job_group.most_recent_job %>
    <%= @smoke_test.most_recent_job_group.most_recent_job.send("#{builder_type}_revision") %>
<% end %>
<% end #end stock builder %>
<% end # end package_builders %>

<% @smoke_test.config_modules.each do |conf_mod| %>
<% if not is_config_module_stock(conf_mod) then %>
<% conf_mod_type = conf_mod.type.chomp('ConfigModule').downcase %>
<h4><%= conf_mod_type.upcase %> Config Module</h4>
<b>URL:</b> <%= conf_mod.url %>
<br/>
<% if not conf_mod.branch.blank? then %>
<b>Branch:</b><%= conf_mod.branch %>
<br/>
<% end %>
<b>Merge trunk:</b><%= yes_no(conf_mod.merge_trunk) %>
<br/>
<b>Revision (most recent):</b>
<% if @smoke_test.most_recent_job_group and @smoke_test.most_recent_job_group.most_recent_job %>
    <%= @smoke_test.most_recent_job_group.most_recent_job.send("#{conf_mod_type}_conf_module_revision") %>
<% end %>
<% end #end stock conf_mod %>
<% end # end config_modules %>
<hr/>

<% @jobs = Job.find(:all, :select => "id, status, type, job_group_id, nova_revision, glance_revision, keystone_revision, swift_revision, cinder_revision, neutron_revision, ceilometer_revision, heat_revision, nova_conf_module_revision, glance_conf_module_revision, keystone_conf_module_revision, swift_conf_module_revision, cinder_conf_module_revision, neutron_conf_module_revision, ceilometer_conf_module_revision, heat_conf_module_revision, msg, config_template_id, created_at, updated_at, start_time, finish_time, approved_by", :conditions => ["job_group_id IN (SELECT id from job_groups WHERE smoke_test_id = ?)", @smoke_test.id], :include => [:config_template,:approved_by_user, {:job_group => :smoke_test}], :order => "id DESC", :limit => 100) %>
<script type="text/javascript">

$(document).ready(function() {

    job_table_selectors();

});

</script>
<table id="jobs-table" class="data">
    <%= render(:partial => '/jobs/table', :locals => {:show_updated_at => true, :show_description => false}) %>
</table>